name       : evopop-gtk-theme
version    : 1.6.1
release    : 13
source     :
    - https://github.com/solus-cold-storage/evopop-gtk-theme/archive/1.6.1.tar.gz : feccbed31e128a8f3ea9aa3ac3bcf1da95581dea3500aac8657a0f96b9fd7408
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
