name       : evopop-gtk-theme
version    : 2.0.3
release    : 19
source     :
    - https://github.com/solus-cold-storage/evopop-gtk-theme/archive/2.0.3.tar.gz : 1dd428d7a388b152597224014fd73038801bc4e639c63d65e942ed5037ff19f3
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
