name       : evopop-gtk-theme
version    : 1.7.2
release    : 14
source     :
    - https://github.com/solus-cold-storage/evopop-gtk-theme/archive/1.7.2.tar.gz : 2ff93b35ac4d99fde25fda2ded1439bcb2c514727b64b6a1fd7f6e4507f5cc0c
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
