name       : evopop-gtk-theme
version    : 2.1.3
release    : 26
source     :
    - https://github.com/solus-project/evopop-gtk-theme/archive/2.1.3.tar.gz : 7342866a0133caac03f854bd1e01ad148112ddadc1c02b571ba141fe33bc754b
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
component  : desktop.theme
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
