name       : evopop-gtk-theme
version    : 0.29
release    : 10
source     :
    - https://github.com/solus-project/evopop-gtk-theme/releases/download/0.29/evopop-gtk-theme-0.29.tar.xz : eab2b3a281f13c0805af0c36259732c55e0ce1af83214e8062d68cc3d52ed54b
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
