name       : evopop-gtk-theme
version    : 1.7.3
release    : 16
source     :
    - https://github.com/solus-cold-storage/evopop-gtk-theme/archive/1.7.3.tar.gz : 346a05e44308afdbc8ce0a5cbdcb2ba55775f9ece3ca56597af5bf0a028814cd
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
