name       : evopop-gtk-theme
version    : 2.0.2
release    : 18
source     :
    - https://github.com/solus-cold-storage/evopop-gtk-theme/archive/2.0.2.tar.gz : f157966a0e8883214df86d016dc9473b73bdc8940598a34c128f2d4bc936e587
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
