name       : evopop-gtk-theme
version    : 1.8.0
release    : 17
source     :
    - https://github.com/solus-cold-storage/evopop-gtk-theme/archive/1.8.0.tar.gz : 5b65f9a6e9f76a10eb5e77a1d0a6d11915b71b5bd3347435328dbb8b1e5af4e8
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Allow symlink update here..
    ln -sv EvoPop $installdir/usr/share/themes/evopop-gtk-theme
